name: flutter_application_1
description: A new Flutter project.
publish_to: 'none' # Remova essa linha se você quiser publicar para pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.3+1               # Adicione o sqflite
  path: ^1.9.0                     # Verifique se a versão é compatível
  cupertino_icons: ^1.0.2          # Para ícones do iOS
  sqflite_common_ffi: ^2.3.3       # Use se você precisar de suporte para FFI

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
